### ISSUE TITLE
Yleaf.py: error: argument -r/--Reads_thresh: invalid int value: 'ef'

### ISSUE THREAD

**Issue by mikaeldahl** [genid/Yleaf#1]
Hi, do you know what might be the problem?

##################   
mikael@mikael-HP-Z600-Workstation[Yleaf] python Yleaf.py -bam /media/hd01/data/genome_mikael/cleanreads/md.chrY.bam -ref hg38 -pos /usr/local/bioinf/Yleaf/hg38.txt -out /media/hd01/data/genome_mikael/cleanreads/ydna_out -r 1 -q 20 -b 90 -t 1
	Erasmus MC Department of Genetic Identification 

	Yleaf: software tool for human Y-chromosomal 
	phylogenetic analysis and haplogroup inference v2.1

    
           |
          /|\          
         /\|/\    
        \\\|///   
         \\|//  
          |||   
          |||    
          |||    

        
usage: Yleaf.py [-h] [-fastq PATH] [-bam PATH] [-f PATH] -pos PATH -out STRING
                [-r READS_THRESH] -q QUALITY_THRESH -b BASE_MAJORITY
                [-t THREADS]
Yleaf.py: error: argument -r/--Reads_thresh: invalid int value: 'ef'

        
usage: Yleaf.py [-h] [-fastq PATH] [-bam PATH] [-f PATH] -pos PATH -out STRING
                [-r READS_THRESH] -q QUALITY_THRESH -b BASE_MAJORITY
                [-t THREADS]
Yleaf.py: error: argument -r/--Reads_thresh: invalid int value: 'ef'
##############

**Comment by dmontielg** [comment]
Hi, 

In case of alignment files such as BAM format you do not need to add [-ref] as a parameter, this will be only to proceed to align raw reads (FastQ format) to the reference human genome. 

You should just exclude the -ref as the following:

python Yleaf.py -bam file.bam -pos Position_files/hg38.txt -out out -r 1 -q 20 -b 90 -t 1

Hope this helps!

Best,
Diego

**Comment by mikaeldahl** [comment]
it did. 
Thank you Diego =)

**Comment by genericusername1199** [comment]
Hi, I get the same error but within FASTQ files as well. I ran the command like in the example mentioned in the README.

python Yleaf.py -fastq S19_19.fastq -out out -r 1 -q 20 -b 90 -t 16 -ref hg38

I receive the same error message as mentioned above.  Am I doing anything obviously incorrect?

Carl

**Comment by dmontielg** [comment]
Hi, 

Sure! When running Yleaf with FASTQ files you first need to create an indexed file with BWA. This is included by running "python install.py". Then, Select the genome build, in your case hg38. This might take a while depending on your network and CPU to download and generate the index reference genome.

Lastly, for running Yleaf you can do something like:

python Yleaf.py -fastq S19_19.fastq -out out -r 1 -q 20 -b 90 -t 16 -pos Position_files/hg38.txt -f hg38/hg38.fasta

Hope this helps!

Best,
Diego

**Comment by genericusername1199** [comment]
Great! That works for me.

Best,

Carl

**Comment by Haike2002** [comment]
Hi 

I've been using Yleaf for the last week and never had a problem. Today I want to run the FastQ of read 1 of a sample but I get following error: 
[E::mpileup] fail to parse region 'None' with /home/haikev/y_leaf/y_leaf/007_KAPA_R1/007_KAPA_R1.bam 

However, if I try with read 2 of the same sample I don't get any errors. Same with another sample: error with read 1 and no problems with read 2  
How do I fix this? I have already updated all installation steps
