### ISSUE TITLE
What if input paired-end reads fastq file

### ISSUE THREAD

**Issue by QianXiaobo** [genid/Yleaf#12]
Hi, my fastq files are generated by paired-end sequencing, so that I have two fq files for each sample (e.g. sample.1.fq.gz and sample.2.fq.gz). Does Yleaf support two fq files input like `-fastq sample.1.fastq -fastq sample.2.fastq`?

Best wishes
Xb

**Comment by ArwinRalf** [comment]
Hi Xb,

Using such an input would not work. There are a few things you could do:
1) Use an aligner of your choosing and analyze the resulting bam files with Yleaf
2) Combine the two fastq files into one and then analyze with Yleaf
3) Analyze the two files separately with Yleaf

My advise would be to use Yleaf on bam files whenever possible, that gives you more liberty to use the aligner of your choosing and to apply the setting that you prefer.

**Comment by QianXiaobo** [comment]
Thank you very much! I will try to use Bam file as input.
