### ISSUE TITLE
Error indicated when running Yleaf installed with conda on CentOs

### ISSUE THREAD

**Issue by thierrygrange** [genid/Yleaf#13]
After a conda install of Yleaf on Centos 7, I receive the following error message. This does not prevent the run but it indicates a problem:
Error processing line 1 of /home/grange/miniconda2/envs/yleaf/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/grange/miniconda2/envs/yleaf/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Any suggestions of script modification or of why this module is not installed?

Thanks

Thierry

**Comment by 6bass6** [comment]
Thank you for your comment. 

It appears the issue can be solved installing the following package: 

pip install -U pip setuptools

Unfortunately, the last developer that worked on Yleaf is no longer employed by us and there is no replacement yet. Once we have a new developer, we can look into modifying the script to prevent this error from occuring. 

Best wishes,
Arwin
