### ISSUE TITLE
Few queries

### ISSUE THREAD

**Issue by Agenetics** [genid/Yleaf#14]
Hi. Thanks for the nice software. I have 2 queries.

1. Is there a way to ignore C->T and G->A SNPs in the tool's prediction? That will be invaluable for ancient DNA.
2. Is there a way to run this on multiple bam files in one command?

Thank you.

**Comment by 6bass6-010** [comment]
Hi,

Apologies for the late response.
1. That function has not been implemented yet; however, I do see how it could be a useful feature. I will try to have it implemented in the next version. 
2. Certainly, if you collect you bam files in a single directory and specify that directory as the input it will automatically analyze all bam files present there. 

Best wishes,
Arwin

**Comment by 6bass6** [comment]
> Hi. Thanks for the nice software. I have 2 queries.
> 
> 1. Is there a way to ignore C->T and G->A SNPs in the tool's prediction? That will be invaluable for ancient DNA.
> 2. Is there a way to run this on multiple bam files in one command?
> 
> Thank you.

The funcionality for aDNA is now implemented in v3.2.1 that was just released
