### ISSUE TITLE
Old Prediction Option not using the correct files

### ISSUE THREAD

**Issue by cascadingstyletrees** [genid/Yleaf#16]
I created #15 as the first of a few changes that are needed to fix the old prediction option.

The next part should be to fix the intermediates.txt file look up since currently it's missing a `/`, so you'd see an error that the file wasn't found at `.../data/hg_prediction_tablesIntermediates.txt` 

One option I found was to change `Intermediates.txt` to `/Intermediates.txt`  at  https://github.com/genid/Yleaf/blob/31cbdcbb881580d1c64b9250b59f946bc3881a27/yleaf/old_predict_haplogroup.py#L283

This however hasn't yet fixed all the issues that I'm having with old predictions.

**Comment by 6bass6** [comment]
Dear cascadingstyletrees,

Apologies for the delay, the problem should be revolved now.

**Comment by serge2016** [comment]
Could you make a new release, please?
