### ISSUE TITLE
output

### ISSUE THREAD

**Issue by ghost** [genid/Yleaf#19]
hi, I want to infer Y-haplogroups of 100 samples using their bam files merged as one, so when I run this tool, (using the command: Yleaf -bam input.bam -o output -rg hg19), in the output folder, the .out file contains haplogroup per position which is confusing, I don't know where to get haplogroups per sample, can you please help me? thanks

**Comment by 6bass6** [comment]
Hi, Yleaf wouldn't function correctly on merged bam files including multiple samples. The easiest would be to undo the merge to obtain 100 individual bam files again and to run Yleaf on those.
