### ISSUE TITLE
Updating position files 

### ISSUE THREAD

**Issue by teepean** [genid/Yleaf#2]
Hi,

I have been updating hg19 position files and came across a problem I am not sure how to deal with. For example Z14 is represented in ISOGG as follows and Yleaf cannot parse that line.

`Z14	R1b1a1b1a1a1b1			17364720..17364737	15252840..15252857	CAGATAGATAGATAGATA->CAGATAGATAGATA`

Thanks!

**Comment by dmontielg** [comment]
Hi, 

Thanks a lot for your comment. Unfortunately, currently, Yleaf does not support the analysis of **indels**, but we might consider implementing this in future versions of the software.

Best,
Diego

**Comment by teepean** [comment]
Thank you for your prompt answer!
