### ISSUE TITLE
Difference in results between Yleaf v3.0.1 and v3.1 (master)

### ISSUE THREAD

**Issue by Stikus** [genid/Yleaf#20]
Hello, after migration from Yleaf v3.0.1 to latest version (not using v3.1 due to https://github.com/genid/Yleaf/pull/15 and https://github.com/genid/Yleaf/issues/16 in v3.1 release) we've got some differences:

Yleaf_version | Sample_name | Hg | Hg_marker | Total_reads | Valid_markers | QC-score | QC-1 | QC-2 | QC-3
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
latest | test | N1~ | N-CTS11499/etc*(xCTS10760,Z4963,B195,Y13851,F859,PF967.2,Y16325,M2118,Y9025,B187,Y24348,FGC10788,F1228,CTS5397) | 4124 | 64768 | 1.0 | 1.0 | 1.0 | 1.0
v3.0.1 | test | N1a1a1a1a2a1a1~ | N-Z1926*(xCTS1737,Y21699) | 5549131 | 64771 | 1.0 | 1.0 | 1.0 | 1.0

You can see two major differences - `Hg` (and `Hg_marker`) and `Total_reads` (and `Valid_markers` btw).

- First difference come from sorting order changed in https://github.com/genid/Yleaf/commit/bc03016e206065eadf036c8f32f31129b7206320:

![image](https://github.com/genid/Yleaf/assets/41360525/ab48ae5d-ea06-4571-b120-12c2b7f3cbca)

Is this intended, that instead of  `N1a1a1a1a2a1a1~` we're getting `N1~`?

---

- Second difference come from code refactoring:

`Total_reads` and `Valid_markers` come from 2nd and last positions of log:
https://github.com/genid/Yleaf/blob/master/yleaf/old_predict_haplogroup.py#L255-L287
```py
def process_log(log_file):
    log_file += "info"
    total_reads = "NA"
    valid_markers = "NA"

    try:
        df_log = pd.read_csv(log_file, sep=":", header=None)
        log_array = df_log[1].values
        total_reads = log_array[1]
        valid_markers = log_array[-1]
    except FileNotFoundError:
        print("Warning: log file not found!")
    return total_reads, valid_markers


def main():
    print("\tY-Haplogroup Prediction")

    args = get_arguments()

    path_samples = args.Input  # .out files are collected
    samples = check_if_folder(path_samples, '.out')
    out_file = args.Outputfile
    hg_intermediate = str(yleaf_constants.DATA_FOLDER / yleaf_constants.HG_PREDICTION_FOLDER)
    intermediate_tree_table = hg_intermediate + "/Intermediates.txt"
    h_flag = True
    log_output = []
    for sample_name in samples:
        putative_hg = "NA"
        out_name = str(sample_name.split("/")[-1])
        out_name = out_name.split(".")[0]

        total_reads, valid_markers = process_log(sample_name[:-3])
```

In `v3.0.1` it was correct:

- https://github.com/genid/Yleaf/blob/3.0.1/Yleaf.py#L509 - first line (`Command`)
- https://github.com/genid/Yleaf/blob/3.0.1/Yleaf.py#L304-L320 - second to last line (`Total_reads`, `Unmapped_reads`, `Valid_markers`)
- https://github.com/genid/Yleaf/blob/3.0.1/Yleaf.py#L562 - log printing - lines from `predict_haplogroup` doesn't appear in log due to previous printing

But now it is not correct:

- https://github.com/genid/Yleaf/blob/master/yleaf/Yleaf.py#L387 - first two lines (`Total_reads`, `Unmapped_reads`)
- https://github.com/genid/Yleaf/blob/master/yleaf/Yleaf.py#L518 - third line (`Valid_markers`)
- https://github.com/genid/Yleaf/blob/master/yleaf/Yleaf.py#L580-L587 - fourth to last line
- https://github.com/genid/Yleaf/blob/master/yleaf/Yleaf.py#L288 - log printing

Log for our data:
```
Total of mapped reads: 5549131
Total of unmapped reads: 4124
Valid markers: 64797
Markers with zero reads: 0
Markers below the read threshold {1}: 0
Markers below the base majority threshold {90}: 28
Markers with discordant genotype: 1
Markers without haplogroup information: 29
Markers with haplogroup information: 64768
```
Now we need first and third line, not second and last.

**Comment by serge2016** [comment]
Looks like hotfix is needed!

**Comment by Stikus** [comment]
Created PR #21 - results after it:
```
< test	N1~	N-CTS11499/etc*(xCTS10760,Z4963,B195,Y13851,F859,PF967.2,Y16325,M2118,Y9025,B187,Y24348,FGC10788,F1228,CTS5397)	5549131	64797	1.0	1.0	1.0	1.0
---
> test	N1a1a1a1a2a1a1~	N-Z1926*(xCTS1737,Y21699)	 5549131	 64771	1.0	1.0	1.0	1.0
```
Only sorting issue left.

**Comment by Stikus** [comment]
@6bass6 @6bass6-010 @dionzand Hello, can anyone answer and check PR?

**Comment by dionzand** [comment]
> @6bass6 @6bass6-010 @dionzand Hello, can anyone answer and check PR?

PR is approved and merged!

**Comment by 6bass6** [comment]
@Stikus regarding the sorting issue, is this a publically available sample? I would like to have a closer look to the data before making changes to the code.

**Comment by Stikus** [comment]
@dionzand thanks for approve and merge.

@6bass6 We used our data as test sample - we can share it, but it is 300MB BAM file - how can we provide it to you?

**Comment by 6bass6** [comment]
@Stikus Please send me an email so we can further discuss the best way to transfer the file.

**Comment by Stikus** [comment]
Can you give me your email? I cannot find any info on GitHub except `32042125+6bass6@users.noreply.github.com` in commits.

**Comment by 6bass6** [comment]
@Stikus you can find it in the Yleaf manual

**Comment by Stikus** [comment]
@6bass6 email sent to both addresses from manual.

**Comment by 6bass6** [comment]
@Stikus an updated version of Yleaf v3.1 in now available where the problems you described are solved. Thank you again for pointing these issues out.

**Comment by Stikus** [comment]
Do you mean master branch? https://github.com/genid/Yleaf/releases/tag/3.1 tag doesn't change.

Do you plan to release some new tag? 3.1.1 maybe?

After update, only minor differences left:
```
< test	N1a1a1a1a2a1a1~	N-Z1926*(xCTS1737,YP4950)	5549131	64797	0.997	1.0	1.0	0.997
---
> test	N1a1a1a1a2a1a1~	N-Z1926*(xCTS1737,Y21699)	 5549131	 64771	1.0	1.0	1.0	1.0

```

I assume they are insignificant?

**Comment by serge2016** [comment]
Dear @6bass6, could you, please, update the release or make a new one?

**Comment by 6bass6** [comment]
@serge2016 we will soon, there are a few things we want to implement first before making a new release. In the meanwhile the issues discussed here are already solved. If you use the [old_predict_haplogroup.py] that was changed 2 days ago you can already see that it functions correctly now.

**Comment by dionzand** [comment]
> Dear @6bass6, could you, please, update the release or make a new one?

The new release v3.2 is now available. I will close this issue now.
