### ISSUE TITLE
2.3 release

### ISSUE THREAD

**Issue by serge2016** [genid/Yleaf#3]
Hello!

Thank you for the tool! Do you plan to release the 2.3 version?

**Comment by Stikus** [comment]
@dmontielg Hello, any news about updates?

Or method to convert ISOGG data to your position file format?

ISOGG data is stored in this type of table:

Name | Subgroup Name | Alternate Names | rs numbers | Build 37 Number | Build 38 Number | Mutation Info
-- | -- | -- | -- | -- | -- | --
L1100 | A (Notes) |   |   | 6851661 | 6983620 | C->T
[maybe L333] | Q1b1a3a1a~ |   |   | 15019573 | 12907662 | T->C
12f2.1 | J |   |   |   |   |  
50f2(P) | B2b1 | M8659 |   | 23497067 | 21335181 | C->G
A100 | R1b1a1b1a1a2c1a1d5a | FGC8628; Y3517 |   | 14032743 | 11912037 | A->T
A10028 | I2a1a2a1a3 |   |   | 2720236 | 2852195 | A->G
A10029 | I2a1a2a1a3 |   |   | 15881295 | 13769415 | C->T
A10030 | I2a1a2a1a3 |   |   | 21666506 | 19504620 | C->T
A10031 | I2a1a2a1a3 |   |   | 21817914 | 19656028 | G->T
A10032 | I2a1a2a1a3 |   |   | 21904388 | 19742502 | T->C
A10033 | I2a1a1b1a1a3~ |   |   | 7625503 | 7757462 | C->A
A10034 | I2a1a1b1a1a3a~ |   |   | 16513268 | 14401388 | T->C
A10035 | I2a1a1b1a1a3a~ |   |   | 16651541 | 14539661 | G->T
A10036 | I2a1a2a1a2b2 |   |   | 14409483 | 12288780 | A->C
A101 | R1b1a1b1a1a2c1a1d5~ | FGC8633; Y3518 |   | 15373303 | 13261423 | C->T
A10110 | I2a1a1b2~ |   |   | 2913202 | 3045161 | G->A
A10111 | I2a1a1b2~ |   |   | 21225818 | 19063932 | A->C
A10112 | I2a1a1b2~ |   |   | 14043980 | 11923274 | T->C
A10123.2 | G2a2b2a1a1b1a1a2a1a1b1d1a~ |   |   | 7064140 | 7196099 | G->C

**Comment by bramvanwersch** [comment]
Hey, sorry for the long wait. The 2.3 version will not be officially released but we will leave the branch open. Today the 3.0 version was released merging the data from YFull and ISOGG. 

@Stikus There is now (as of version 3.0) the possibility to compile the ISOGG table into tables that Yleaf can read using [convert_ISOGG_table.py](https://github.com/genid/Yleaf/blob/master/convert_ISOGG_table.py). For more information take a look at the [yleaf_manual.pdf](https://github.com/genid/Yleaf/blob/master/yleaf_manual.pdf).
