### ISSUE TITLE
Article link in the readme is broken

### ISSUE THREAD

**Issue by serge2016** [genid/Yleaf#4]
Hello!

The link in the readme points to: https://academic.oup.com/mbe/article/35/7/1820/4993044, which is:
```
This is a correction to:
Molecular Biology and Evolution, Volume 35, Issue 5, May 2018, Pages 1291–1294, https://doi.org/10.1093/molbev/msy032
This article published with a comment intended only to the editors of the journal. The comment has been removed. The author regrets the error.
```

So the correct link is the original one?  
https://academic.oup.com/mbe/article/35/5/1291/4922696

**Comment by bramvanwersch** [comment]
Hey, sorry for the long wait on answering your question. I have changed the link. 

Thank you for notifying us.
