### ISSUE TITLE
How to choose the position files?

### ISSUE THREAD

**Issue by baif666** [genid/Yleaf#6]
Hi genid, I found there are three versions of 'Position File' (MCS_Ampliseq/Visage_Ampliseq/WGS). What are the differences between them? How to choose one? I use the GRCh37 (100 genomes) as the reference and I don't know which one I can use. Thanks!

**Comment by bramvanwersch** [comment]
Hey @baif666, the position file you want to use is the [Position_files/WGS_hg19.txt](https://github.com/genid/Yleaf/blob/master/Position_files/WGS_hg19.txt). 

Soon (hopefully today) a new version of the software will release. Here the position files will be cleaned up a bit as well as an improved version of the haplogroup tree will be added.

**Comment by baif666** [comment]
Thanks!
