### ISSUE TITLE
Docs: mention the support of alignment.bam.bai only, not alignment.bai

### ISSUE THREAD

**Issue by serge2016** [genid/Yleaf#9]
Hello!

Thank you for this great tool! I think it would be great to mention in the readme, that the index file for input BAM-file should be named as `alignment.bam.bai`, not `alignment.bai`. This restriction is due to this line: https://github.com/genid/Yleaf/blob/master/Yleaf.py#L434

And this is not obvious, because different tools process differently named indesxes.

**Comment by bramvanwersch** [comment]
Hey,

My apologies for the late reply. Thank you for your comment. This is indeed unclear. I added a very small update that allows the program to recognize both naming schemes. You can download the new update by pulling the latest commits.
